bot_token = ""

# Задержка перед ответом бота в секундах. Может быть целым числом или десятичной дробью.
response_delay = 0.0

# Шанс ответа в процентах (>0, <=100). Может быть целым числом или десятичной дробью.
response_chance = 100.0
