[tool.black]
line-length = 80
target-version = ["py37"]
skip-magic-trailing-comma = true
preview = true

[tool.mypy]
python_version = "3.7"
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = false
warn_unreachable = true
local_partial_types = true
enable_error_code = [
  "redundant-self",
  "redundant-expr",
  "possibly-undefined",
  "truthy-bool",
  "truthy-iterable",
  "ignore-without-code",
  "unused-awaitable",
]
strict = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = ["markovify.*", "vkbottle.*", "vkbottle_types.*"]
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.ruff]
ignore = [
  "ANN",
  "BLE001",
  "C901",
  "COM",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D203",
  "D205",
  "D212",
  "D213",
  "D400",
  "D401",
  "D407",
  "D415",
  "D417",
  "DJ008",
  "ERA001",
  "FBT002",
  "PD901",
  "PERF203",
  "PLR0911",
  "PLR0912",
  "PLR0913",
  "PLR0915",
  "PT012",
  "RUF001",
  "RUF002",
  "RUF003",
  "RUF012",
  "RUF013",
  "S110",
  "S112",
  "S308",
  "S311",
  "SIM105",
  "TCH001",
  "TCH002",
  "TCH003",
  "TID252",
  "TRY400",
]
ignore-init-module-imports = true
line-length = 80
select = ["ALL"]
target-version = "py37"

[tool.ruff.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.pyupgrade]
keep-runtime-typing = true
